### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SamEsmailR** [cywio/bullet#1]
Hi there i was looking for a UI for dokku and came across your awesome repo . But even after adding the Database URL in env file the web app doesn't work . No login or registration is working.
ps I have already installed dokku on ubuntu 20 and I am running the code on that same machine

**Comment by cywio** [comment]
Hello! Sorry for the late reply, as of yesterday I created a Dockerfile and install script so now you should be able to install it without manually doing it. It might still be a bit rough so feel free to let me know if the installation or parts of the app does not work. Thanks!

I also wrote up a little bit of documentation you can view on installing it here: [https://cyw.io/bullet](https://cyw.io/bullet)

**Comment by cywio** [comment]
Yes, if you look at the contents of the install script it should be pretty self explanatory how it's done since its installed like any other dokku deployment, just with some extras. Ill add in some more info into the docs for a manual installation in a little bit as well. Thanks!

**Comment by SamEsmailR** [comment]
yeah i just saw the script .can we have a discord server to chat https://discord.gg/92uPe8fUFS. I don't want to leave my questions as issues here. Thanks
