### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by sawa-ko** [cywio/bullet#3]
I see that the documentation page does not work and neither do the installation instructions, I also see a PR that improves many things that have not been reviewed, etc.

**Comment by jyoost** [comment]
Works fine for me!  The documentation is excellent!

**Comment by sawa-ko** [comment]
@jyoost Where is the documentation? The links in the README do not work.

**Comment by jyoost** [comment]
Follow the instructions in README

**Comment by sawa-ko** [comment]
@jyoost i cant install. 😢

![image](https://user-images.githubusercontent.com/56084970/186966723-d9d8e742-33fe-4bff-a94f-40a026e9d7ac.png)

![image](https://user-images.githubusercontent.com/56084970/186967869-cf7e1d22-6883-4dad-93b1-9ba1d315dca6.png)

![image](https://user-images.githubusercontent.com/56084970/186966513-1e085279-2ea7-4384-add3-157ca73939b0.png)

**Comment by jyoost** [comment]
What OS are you using?

**Comment by sawa-ko** [comment]
@jyoost Oracle Linux/arm (Ubuntu 20.04) instance.
